#!/usr/bin/env bash
# A script that generates a MySQL dump and creates a compressed archive

mysqldump -u root --password="$1" --all-databases > backup.sql
tar -czf "$(date +%d-%m-%Y)".tar.gz backup.sql
