#!/usr/bin/env bash
# This bash script displays "Best School" 10 times using a for loop

file="/etc/passwd"
while IFS=: read -r user password uid group user_info home shell;
	do
		echo -n "The user $user is part of the $group gang, "
		echo -n "lives in $home and rides $shell. "
		echo -n "$uid's place is protected by the passcode $password, "
		echo "more info about the user here: $user_info"
	done < "$file"
