#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

number=1

while [ $number -le 20 ]; do
    case $number in
        4)
            printf "%s\nbad luck from China\n" $number
            ;;
        9)
            printf "%s\nbad luck from Japan\n" $number
            ;;
        17)
            printf "%s\nbad luck from Italy\n" $number
            ;;
        *)
            echo "$number"
            ;;
    esac
    ((number++))
done
